on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version to release (ex. `2026.1.0`)"
        required: true
        type: string

name: Manual release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository at release tag
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.version }}
      - name: Create copy of vendordep.json
        run: cp vendordep.json DogLog-${{ inputs.version }}.json
      - name: Create Vendor JSON Repo PR
        uses: wpilibsuite/vendor-json-repo/.github/actions/add_vendordep@main
        with:
          repo: jonahsnider/vendor-json-repo
          token: ${{ secrets.DOGLOG_VENDORDEP_ACCESS_TOKEN }}
          vendordep_file: ${{ github.workspace }}/DogLog-${{ inputs.version }}.json
          pr_title: "Add DogLog v${{ inputs.version }}"
          pr_branch: "doglog-v${{ inputs.version }}"
